incidents_raw_data_path = '../Data/Autogenerated/gun-violence-data_01-2013_03-2018.csv'
incidents_clean_data_path = '../Data/Autogenerated/gun-violence-data_01-2013_03-2018_clean.csv'
incidents_clean_data_demograph_path = '../Data/Autogenerated/gun-violence-data_01-2013_03-2018_clean_demo.csv'
states_data_path = '../Data/Static/states.csv'